version: "3.8"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env 
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/taskmanager
      - REDIS_HOST=redis
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
